/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.bean.Relatorio;
import model.dao.RelatorioDAO;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author William
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */

    RelatorioDAO rdao = new RelatorioDAO();
    
    public Grafico() {
        setTitle("Gráfico Casos");
        setSize(512,400);
        setLocationRelativeTo(null);
        criarGrafico();
        setVisible(false);
    }
    
    
    public void criarGrafico() {
        DefaultCategoryDataset linha = new DefaultCategoryDataset();
        

       
        for (Relatorio r : rdao.read()) {
           
            linha.addValue(r.getPercent(),r.getCidadeNome()+" ("+r.getPopulacao()+")",r.getDataCasos()); 
        }        
        
        JFreeChart grafico = ChartFactory.createLineChart("Evolução do Casos","Dias","Porcentagem da população",linha,PlotOrientation.VERTICAL,true,true,true);
        ChartPanel painel = new ChartPanel(grafico);
        add(painel);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
